### ISSUE TITLE
Stella's Roadmap

### ISSUE THREAD

**Issue by yazaldefilimone** [yazaldefilimone/stella#2]
<samp>

Welcome to the stella wiki!

1. Lexer and Parser
- [x] Implement full lexer for Lua 5.4
  - Include all tokens: keywords, operators, delimiters, literals
  - E.g. `and`, `break`, `do`, `else`, `elseif`, `end`, `false`, `for`, `function`, `if`, `in`, `local`, `nil`, `not`, `or`, `repeat`, `return`, `then`, `true`, `until`, `while`
- [x] Create parser for all Lua structures
  - Expressions, statements, functions, tables, etc.
- [x] Add support for new type tokens and structures
  - E.g. `type`, `enum`, `:`, `|` (for union types)

2. Type System
- [ ] Implement primitive types: nil, boolean, number, string, function, thread, userdata
- [ ] Create system for compound types:
  - [ ] Tables (with types for keys and values)
  - [ ] Functions (with types for parameters and return)
  - [ ] Union types (e.g. `number | string`)
  - [ ] Named types (e.g. `type Point = { x: number, y: number }` | `type Point = { x = number, y = number }`)
  - [ ] Enums (e.g. `enum Color { Red, Green, Blue }`)
- [ ] Implement subtyping and type compatibility system

3. Semantic Analysis
- [ ] Implement scope analysis
  - Local variables, globals, upvalues
  - Shadowing and name resolution
- [ ] Create symbol system and symbol table
- [ ] Implement check for use of undeclared variables

4. Type Inference
- [ ] Develop inference algorithm for:
  - [ ] Arithmetic and logical expressions
  - [x] Function calls
  - [ ] Table construction and access
  - [ ] Loops and control structures
- [ ] Implement bidirectional inference
- [ ] Add support for inference in closures

5. Type Checking
- [ ] Implement checking for all Lua expressions
  - [ ] Arithmetic operators: `+`, `-`, `*`, `/`, `//`, `^`, `%`
  - [x] Concatenation operator: `..`
  - [ ] Relational operators: `<`, `>`, `<=`, `>=`, `==`, `~=`
  - [ ] Logical operators: `and`, `or`, `not`
- [ ] Add checking for statements
  - [ ] `if`, `elseif`, `else`, `while`, `repeat`, `for`, `do`
- [ ] Implement type checking for functions
  - [ ] Parameters, 
  - [ ] returns
  - [ ] variadic functions (`...`)
- [ ] Add checking for metatables and metamethods

6. Support for Lua-Specific Features
- [ ] Implement support for type coercion (e.g. string to number)
- [ ] Add handling for `nil` and nullability checking
- [ ] Implement support for `pcall` and `xpcall`
- [ ] Add checking for length operator (`#`)
- [ ] Implement support for modules and `require`

7. Type Extensions
- [x] Create syntax and semantics for type annotations
  - eg. `local x: number = 10`
  - eg. `function add(a: number, b: number): number`
- [ ] Implement type declarations
  - eg. `type Point = { x: number, y: number }`
- [ ] Add support for enums
  - eg. `enum Direction { North, South, East, West }`
- [ ] Implement generic types
  - eg. `type Array<T> = { [number]: T }`

8. Error System and Reporting
- [x] Develop detailed error message system
- [x] Implement precise error location tracking (file, line, column)
- [ ] Create warning system for potential type issues

9. Optimization and Performance
- [ ] Implement caching of types for common expressions
- [ ] Optimize type unification algorithm
- [ ] Add support for incremental analysis

10. Integration and Tooling
- [ ] Create CLI for the type checker
- [ ] Implement generation of type definition files (.d.lua)
- [ ] Develop integrations with popular IDEs/editors

11. Testing and Documentation
- [ ] Create comprehensive test suite covering all Lua features
- [ ] Implement integration tests with existing Lua codebases
- [ ] Develop detailed technical documentation of the type system
